2023-06-18 22:50:11,000 INFO server.py Function get_message was called - args: (<socket.socket fd=528, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59736)>,), kwargs: {}. It was called from function server.main()
2023-06-18 22:50:11,000 INFO server.py Received message from client cat: {'action': 'presence', 'time': 1687117810.5155783, 'user': {'username': 'cat', 'status': 'online'}, 'type': 'status'}
2023-06-18 22:50:11,000 INFO server.py Function send_message was called - args: (<socket.socket fd=528, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59736)>, {'action': 'login', 'time': 1687117811.0005014, 'alert': 'ok'}), kwargs: {}. It was called from function server.main()
2023-06-18 22:50:11,000 INFO server.py Response message was sent: {'action': 'login', 'time': 1687117811.0005014, 'alert': 'ok'}
2023-06-18 22:50:11,000 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x000001E05F00EA10>, [<socket.socket fd=528, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59736)>]), kwargs: {}. It was called from function server.main()
2023-06-18 22:50:17,031 INFO server.py Function get_message was called - args: (<socket.socket fd=524, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59733)>,), kwargs: {}. It was called from function server.main()
2023-06-18 22:50:17,031 INFO server.py Received message from client dog: {'action': 'presence', 'time': 1687117816.0747323, 'user': {'username': 'dog', 'status': 'online'}, 'type': 'status'}
2023-06-18 22:50:17,031 INFO server.py Function send_message was called - args: (<socket.socket fd=524, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59733)>, {'action': 'login', 'time': 1687117817.0317698, 'alert': 'ok'}), kwargs: {}. It was called from function server.main()
2023-06-18 22:50:17,031 INFO server.py Response message was sent: {'action': 'login', 'time': 1687117817.0317698, 'alert': 'ok'}
2023-06-18 22:50:17,031 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x000001E05F00EA10>, [<socket.socket fd=524, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59733)>]), kwargs: {}. It was called from function server.main()
2023-06-18 22:50:24,059 ERROR server.py Client ('127.0.0.1', 59733) disconnected, error [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2023-06-18 22:50:24,059 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x000001E05F00EA10>, [<socket.socket fd=524, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59733)>]), kwargs: {}. It was called from function server.main()
2023-06-18 22:50:38,586 INFO server.py The connection was set - client: <socket.socket fd=324, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60010)>, address: ('127.0.0.1', 60010)
2023-06-18 22:50:39,010 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-18 22:50:39,010 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function server.main()
2023-06-18 22:50:39,027 ERROR server.py Something went wrong: [WinError 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
2023-06-18 22:50:51,693 INFO server.py Function get_message was called - args: (<socket.socket fd=324, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60010)>,), kwargs: {}. It was called from function server.main()
2023-06-18 22:50:51,694 INFO server.py Received message from client cat: {'action': 'presence', 'time': 1687117850.7674851, 'user': {'username': 'cat', 'status': 'online'}, 'type': 'status'}
2023-06-18 22:50:51,694 INFO server.py Function send_message was called - args: (<socket.socket fd=324, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60010)>, {'action': 'login', 'time': 1687117851.6940012, 'alert': 'error'}), kwargs: {}. It was called from function server.main()
2023-06-18 22:50:51,695 INFO server.py Response message was sent: {'action': 'login', 'time': 1687117851.6940012, 'alert': 'error'}
2023-06-18 22:50:51,695 ERROR server.py Client ('127.0.0.1', 60010) disconnected, error too many values to unpack (expected 2)
2023-06-18 22:50:51,695 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x000001E05F00EA10>, [<socket.socket fd=324, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60010)>]), kwargs: {}. It was called from function server.main()
2023-06-18 22:52:31,065 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-18 22:52:31,067 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function server.main()
2023-06-18 22:52:31,074 ERROR server.py Something went wrong: [WinError 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
2023-06-18 22:52:31,632 INFO server.py The connection was set - client: <socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60466)>, address: ('127.0.0.1', 60466)
2023-06-18 22:52:43,718 INFO server.py Function get_message was called - args: (<socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60466)>,), kwargs: {}. It was called from function server.main()
2023-06-18 22:52:43,721 INFO server.py Received message from client mouse: {'action': 'presence', 'time': 1687117963.1283612, 'user': {'username': 'mouse', 'status': 'online'}, 'type': 'status'}
2023-06-18 22:52:43,723 INFO server.py Function send_message was called - args: (<socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60466)>, {'action': 'login', 'time': 1687117963.722858, 'alert': 'ok'}), kwargs: {}. It was called from function server.main()
2023-06-18 22:52:43,723 INFO server.py Response message was sent: {'action': 'login', 'time': 1687117963.722858, 'alert': 'ok'}
2023-06-18 22:52:43,724 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x000001E05F00EA10>, [<socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60466)>]), kwargs: {}. It was called from function server.main()
2023-06-18 22:53:34,112 INFO server.py Function get_message was called - args: (<socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60466)>,), kwargs: {}. It was called from function server.main()
2023-06-18 22:53:34,112 INFO server.py Received message from client mouse: {'action': 'msg', 'time': 1687118013.2579124, 'user': {'username': 'mouse', 'status': 'online'}, 'body': 'hi', 'to_user': 'bird'}
2023-06-18 22:53:34,113 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x000001E05F00EA10>, [<socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60466)>]), kwargs: {}. It was called from function server.main()
2023-06-18 22:53:34,113 ERROR server.py User bird is not registered, message can not be sent
2023-06-18 22:53:34,114 INFO server.py Function write_responses was called - args: (<__main__.Server object at 0x000001E05F00EA10>, [<socket.socket fd=528, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59736)>, <socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60466)>]), kwargs: {}. It was called from function server.main()
2023-06-18 22:54:45,655 INFO server.py Function get_message was called - args: (<socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60466)>,), kwargs: {}. It was called from function server.main()
2023-06-18 22:54:45,657 INFO server.py Received message from client mouse: {'action': 'msg', 'time': 1687118084.8090456, 'user': {'username': 'mouse', 'status': 'online'}, 'body': 'hi', 'to_user': 'cat'}
2023-06-18 22:54:45,659 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x000001E05F00EA10>, [<socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60466)>]), kwargs: {}. It was called from function server.main()
2023-06-18 22:54:45,660 INFO server.py Function send_message was called - args: (<socket.socket fd=528, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59736)>, {'action': 'msg', 'time': 1687118084.8090456, 'user': {'username': 'mouse', 'status': 'online'}, 'body': 'hi', 'to_user': 'cat'}), kwargs: {}. It was called from function server.main()
2023-06-18 22:54:45,662 INFO server.py A message was sent to user: cat from user mouse
2023-06-18 22:54:45,662 INFO server.py Function write_responses was called - args: (<__main__.Server object at 0x000001E05F00EA10>, [<socket.socket fd=528, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59736)>, <socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60466)>]), kwargs: {}. It was called from function server.main()
2023-06-18 22:55:25,014 INFO server.py Function get_message was called - args: (<socket.socket fd=528, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59736)>,), kwargs: {}. It was called from function server.main()
2023-06-18 22:55:25,014 INFO server.py Received message from client cat: {'action': 'msg', 'time': 1687118124.2663038, 'user': {'username': 'cat', 'status': 'online'}, 'body': 'hi', 'to_user': 'cow'}
2023-06-18 22:55:25,017 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x000001E05F00EA10>, [<socket.socket fd=528, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59736)>]), kwargs: {}. It was called from function server.main()
2023-06-18 22:55:25,017 ERROR server.py User cow is not registered, message can not be sent
2023-06-18 22:55:25,018 INFO server.py Function write_responses was called - args: (<__main__.Server object at 0x000001E05F00EA10>, [<socket.socket fd=528, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59736)>, <socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60466)>]), kwargs: {}. It was called from function server.main()
2023-06-18 22:55:57,238 INFO server.py Function get_message was called - args: (<socket.socket fd=528, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59736)>,), kwargs: {}. It was called from function server.main()
2023-06-18 22:55:57,238 INFO server.py Received message from client cat: {'action': 'msg', 'time': 1687118156.2429647, 'user': {'username': 'cat', 'status': 'online'}, 'body': 'hi', 'to_user': 'mouse'}
2023-06-18 22:55:57,239 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x000001E05F00EA10>, [<socket.socket fd=528, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59736)>]), kwargs: {}. It was called from function server.main()
2023-06-18 22:55:57,240 INFO server.py Function send_message was called - args: (<socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60466)>, {'action': 'msg', 'time': 1687118156.2429647, 'user': {'username': 'cat', 'status': 'online'}, 'body': 'hi', 'to_user': 'mouse'}), kwargs: {}. It was called from function server.main()
2023-06-18 22:55:57,241 INFO server.py A message was sent to user: mouse from user cat
2023-06-18 22:55:57,241 INFO server.py Function write_responses was called - args: (<__main__.Server object at 0x000001E05F00EA10>, [<socket.socket fd=528, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59736)>, <socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60466)>]), kwargs: {}. It was called from function server.main()
2023-06-18 23:08:02,010 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-18 23:08:02,011 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function server.main()
2023-06-18 23:08:02,018 INFO server.py Socket was successfully created
2023-06-18 23:08:02,019 INFO server.py Function init_socket was called - args: (<__main__.Server object at 0x00000261A24DEA10>,), kwargs: {}. It was called from function server.main()
2023-06-18 23:08:02,450 INFO server.py The connection was set - client: <socket.socket fd=320, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64202)>, address: ('127.0.0.1', 64202)
2023-06-18 23:08:02,481 INFO server.py The connection was set - client: <socket.socket fd=368, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64207)>, address: ('127.0.0.1', 64207)
2023-06-18 23:08:32,709 INFO server.py Function get_message was called - args: (<socket.socket fd=368, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64207)>,), kwargs: {}. It was called from function server.main()
2023-06-18 23:08:32,710 INFO server.py Received message from client lol: {'action': 'presence', 'time': 1687118911.8226378, 'user': {'username': 'lol', 'status': 'online'}, 'type': 'status'}
2023-06-18 23:08:32,711 INFO server.py Function send_message was called - args: (<socket.socket fd=368, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64207)>, {'action': 'login', 'time': 1687118912.710558, 'alert': 'ok'}), kwargs: {}. It was called from function server.main()
2023-06-18 23:08:32,711 INFO server.py Response message was sent: {'action': 'login', 'time': 1687118912.710558, 'alert': 'ok'}
2023-06-18 23:08:32,712 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x00000261A24DEA10>, [<socket.socket fd=368, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64207)>]), kwargs: {}. It was called from function server.main()
2023-06-18 23:08:38,772 INFO server.py Function get_message was called - args: (<socket.socket fd=320, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64202)>,), kwargs: {}. It was called from function server.main()
2023-06-18 23:08:38,772 INFO server.py Received message from client lala: {'action': 'presence', 'time': 1687118918.4281857, 'user': {'username': 'lala', 'status': 'online'}, 'type': 'status'}
2023-06-18 23:08:38,773 INFO server.py Function send_message was called - args: (<socket.socket fd=320, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64202)>, {'action': 'login', 'time': 1687118918.772205, 'alert': 'ok'}), kwargs: {}. It was called from function server.main()
2023-06-18 23:08:38,773 INFO server.py Response message was sent: {'action': 'login', 'time': 1687118918.772205, 'alert': 'ok'}
2023-06-18 23:08:38,774 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x00000261A24DEA10>, [<socket.socket fd=320, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64202)>]), kwargs: {}. It was called from function server.main()
2023-06-18 23:08:42,800 ERROR server.py Client ('127.0.0.1', 64202) disconnected, error [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2023-06-18 23:08:42,812 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x00000261A24DEA10>, [<socket.socket fd=320, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64202)>]), kwargs: {}. It was called from function server.main()
2023-06-19 10:39:00,937 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 10:39:00,954 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function server.main()
2023-06-19 10:39:00,962 INFO server.py Socket was successfully created
2023-06-19 10:39:00,963 INFO server.py Function init_socket was called - args: (<__main__.Server object at 0x0000019D8A67EB90>,), kwargs: {}. It was called from function server.main()
2023-06-19 10:39:01,505 INFO server.py The connection was set - client: <socket.socket fd=460, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53645)>, address: ('127.0.0.1', 53645)
2023-06-19 10:39:02,101 INFO server.py The connection was set - client: <socket.socket fd=484, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53650)>, address: ('127.0.0.1', 53650)
2023-06-19 10:39:02,571 INFO server.py The connection was set - client: <socket.socket fd=464, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53651)>, address: ('127.0.0.1', 53651)
2023-06-19 10:39:05,590 INFO server.py Function get_message was called - args: (<socket.socket fd=464, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53651)>,), kwargs: {}. It was called from function server.main()
2023-06-19 10:39:05,590 INFO server.py Received message from client cat: {'action': 'presence', 'time': 1687160345.4689946, 'user': {'username': 'cat', 'status': 'online'}, 'type': 'status'}
2023-06-19 10:39:05,591 INFO server.py Function send_message was called - args: (<socket.socket fd=464, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53651)>, {'action': 'login', 'time': 1687160345.5903847, 'alert': 'ok'}), kwargs: {}. It was called from function server.main()
2023-06-19 10:39:05,591 INFO server.py Response message was sent: {'action': 'login', 'time': 1687160345.5903847, 'alert': 'ok'}
2023-06-19 10:39:05,591 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=464, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53651)>]), kwargs: {}. It was called from function server.main()
2023-06-19 10:39:21,730 INFO server.py Function get_message was called - args: (<socket.socket fd=484, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53650)>,), kwargs: {}. It was called from function server.main()
2023-06-19 10:39:21,731 INFO server.py Received message from client dog: {'action': 'presence', 'time': 1687160361.5299711, 'user': {'username': 'dog', 'status': 'online'}, 'type': 'status'}
2023-06-19 10:39:21,731 INFO server.py Function send_message was called - args: (<socket.socket fd=484, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53650)>, {'action': 'login', 'time': 1687160361.7312346, 'alert': 'ok'}), kwargs: {}. It was called from function server.main()
2023-06-19 10:39:21,732 INFO server.py Response message was sent: {'action': 'login', 'time': 1687160361.7312346, 'alert': 'ok'}
2023-06-19 10:39:21,732 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=484, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53650)>]), kwargs: {}. It was called from function server.main()
2023-06-19 10:39:28,785 INFO server.py Function get_message was called - args: (<socket.socket fd=460, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53645)>,), kwargs: {}. It was called from function server.main()
2023-06-19 10:39:28,785 INFO server.py Received message from client mouse: {'action': 'presence', 'time': 1687160368.0464225, 'user': {'username': 'mouse', 'status': 'online'}, 'type': 'status'}
2023-06-19 10:39:28,786 INFO server.py Function send_message was called - args: (<socket.socket fd=460, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53645)>, {'action': 'login', 'time': 1687160368.7857301, 'alert': 'ok'}), kwargs: {}. It was called from function server.main()
2023-06-19 10:39:28,786 INFO server.py Response message was sent: {'action': 'login', 'time': 1687160368.7857301, 'alert': 'ok'}
2023-06-19 10:39:28,788 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=460, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53645)>]), kwargs: {}. It was called from function server.main()
2023-06-19 10:39:42,874 INFO server.py Function get_message was called - args: (<socket.socket fd=460, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53645)>,), kwargs: {}. It was called from function server.main()
2023-06-19 10:39:42,875 INFO server.py Received message from client mouse: {'action': 'msg', 'time': 1687160381.9236205, 'user': {'username': 'mouse', 'status': 'online'}, 'body': 'hey', 'to_user': 'dog'}
2023-06-19 10:39:42,875 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=460, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53645)>]), kwargs: {}. It was called from function server.main()
2023-06-19 10:39:42,875 INFO server.py Function send_message was called - args: (<socket.socket fd=484, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53650)>, {'action': 'msg', 'time': 1687160381.9236205, 'user': {'username': 'mouse', 'status': 'online'}, 'body': 'hey', 'to_user': 'dog'}), kwargs: {}. It was called from function server.main()
2023-06-19 10:39:42,876 INFO server.py A message was sent to user: dog from user mouse
2023-06-19 10:39:42,877 INFO server.py Function write_responses was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=460, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53645)>, <socket.socket fd=484, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53650)>, <socket.socket fd=464, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53651)>]), kwargs: {}. It was called from function server.main()
2023-06-19 10:40:19,150 INFO server.py Function get_message was called - args: (<socket.socket fd=464, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53651)>,), kwargs: {}. It was called from function server.main()
2023-06-19 10:40:19,173 ERROR server.py Client ('127.0.0.1', 53651) disconnected, error 'user'
2023-06-19 10:40:19,174 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=464, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53651)>]), kwargs: {}. It was called from function server.main()
2023-06-19 10:41:27,738 INFO server.py Function get_message was called - args: (<socket.socket fd=484, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53650)>,), kwargs: {}. It was called from function server.main()
2023-06-19 10:41:27,739 INFO server.py Received message from client dog: {'action': 'msg', 'time': 1687160487.2455049, 'user': {'username': 'dog', 'status': 'online'}, 'body': 'woof', 'to_user': 'mouse'}
2023-06-19 10:41:27,739 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=484, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53650)>]), kwargs: {}. It was called from function server.main()
2023-06-19 10:41:27,740 INFO server.py Function send_message was called - args: (<socket.socket fd=460, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53645)>, {'action': 'msg', 'time': 1687160487.2455049, 'user': {'username': 'dog', 'status': 'online'}, 'body': 'woof', 'to_user': 'mouse'}), kwargs: {}. It was called from function server.main()
2023-06-19 10:41:27,742 INFO server.py A message was sent to user: mouse from user dog
2023-06-19 10:41:27,742 INFO server.py Function write_responses was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=460, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53645)>, <socket.socket fd=484, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53650)>]), kwargs: {}. It was called from function server.main()
2023-06-19 10:41:37,398 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 10:41:37,399 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function server.main()
2023-06-19 10:41:37,404 ERROR server.py Something went wrong: [WinError 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
2023-06-19 10:41:37,905 INFO server.py The connection was set - client: <socket.socket fd=500, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 54279)>, address: ('127.0.0.1', 54279)
2023-06-19 10:41:41,946 INFO server.py Function get_message was called - args: (<socket.socket fd=500, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 54279)>,), kwargs: {}. It was called from function server.main()
2023-06-19 10:41:41,947 INFO server.py Received message from client cat: {'action': 'presence', 'time': 1687160501.1447601, 'user': {'username': 'cat', 'status': 'online'}, 'type': 'status'}
2023-06-19 10:41:41,951 INFO server.py Function send_message was called - args: (<socket.socket fd=500, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 54279)>, {'action': 'login', 'time': 1687160501.9507942, 'alert': 'error'}), kwargs: {}. It was called from function server.main()
2023-06-19 10:41:41,953 INFO server.py Response message was sent: {'action': 'login', 'time': 1687160501.9507942, 'alert': 'error'}
2023-06-19 10:41:41,954 ERROR server.py Client ('127.0.0.1', 54279) disconnected, error too many values to unpack (expected 2)
2023-06-19 10:41:41,955 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=500, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 54279)>]), kwargs: {}. It was called from function server.main()
2023-06-19 10:42:53,942 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 10:42:53,944 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function server.main()
2023-06-19 10:42:53,949 ERROR server.py Something went wrong: [WinError 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
2023-06-19 10:42:54,554 INFO server.py The connection was set - client: <socket.socket fd=432, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 54592)>, address: ('127.0.0.1', 54592)
2023-06-19 10:43:03,654 INFO server.py Function get_message was called - args: (<socket.socket fd=432, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 54592)>,), kwargs: {}. It was called from function server.main()
2023-06-19 10:43:03,654 INFO server.py Received message from client horse: {'action': 'presence', 'time': 1687160582.7747364, 'user': {'username': 'horse', 'status': 'online'}, 'type': 'status'}
2023-06-19 10:43:03,655 INFO server.py Function send_message was called - args: (<socket.socket fd=432, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 54592)>, {'action': 'login', 'time': 1687160583.6555257, 'alert': 'ok'}), kwargs: {}. It was called from function server.main()
2023-06-19 10:43:03,656 INFO server.py Response message was sent: {'action': 'login', 'time': 1687160583.6555257, 'alert': 'ok'}
2023-06-19 10:43:03,657 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=432, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 54592)>]), kwargs: {}. It was called from function server.main()
2023-06-19 10:43:08,698 INFO server.py Function get_message was called - args: (<socket.socket fd=432, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 54592)>,), kwargs: {}. It was called from function server.main()
2023-06-19 10:43:08,699 ERROR server.py Client ('127.0.0.1', 54592) disconnected, error 'user'
2023-06-19 10:43:08,700 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=432, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 54592)>]), kwargs: {}. It was called from function server.main()
2023-06-19 11:15:23,074 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 11:15:23,076 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function server.main()
2023-06-19 11:15:23,083 ERROR server.py Something went wrong: [WinError 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
2023-06-19 11:15:23,760 INFO server.py The connection was set - client: <socket.socket fd=500, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62419)>, address: ('127.0.0.1', 62419)
2023-06-19 11:15:24,432 INFO server.py The connection was set - client: <socket.socket fd=444, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62422)>, address: ('127.0.0.1', 62422)
2023-06-19 11:16:01,711 INFO server.py Function get_message was called - args: (<socket.socket fd=444, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62422)>,), kwargs: {}. It was called from function <module>
2023-06-19 11:16:01,712 INFO server.py Received message from client carrot: {'action': 'presence', 'time': 1687162561.197957, 'user': {'username': 'carrot', 'status': 'online'}, 'type': 'status'}
2023-06-19 11:16:01,713 INFO server.py Function send_message was called - args: (<socket.socket fd=444, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62422)>, {'action': 'login', 'time': 1687162561.712124, 'alert': 'ok'}), kwargs: {}. It was called from function <module>
2023-06-19 11:16:01,713 INFO server.py Response message was sent: {'action': 'login', 'time': 1687162561.712124, 'alert': 'ok'}
2023-06-19 11:16:01,714 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=444, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62422)>]), kwargs: {}. It was called from function <module>
2023-06-19 11:16:12,808 INFO server.py Function get_message was called - args: (<socket.socket fd=500, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62419)>,), kwargs: {}. It was called from function <module>
2023-06-19 11:16:12,809 INFO server.py Received message from client tomato: {'action': 'presence', 'time': 1687162572.7082584, 'user': {'username': 'tomato', 'status': 'online'}, 'type': 'status'}
2023-06-19 11:16:12,810 INFO server.py Function send_message was called - args: (<socket.socket fd=500, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62419)>, {'action': 'login', 'time': 1687162572.8095179, 'alert': 'ok'}), kwargs: {}. It was called from function <module>
2023-06-19 11:16:12,810 INFO server.py Response message was sent: {'action': 'login', 'time': 1687162572.8095179, 'alert': 'ok'}
2023-06-19 11:16:12,810 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=500, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62419)>]), kwargs: {}. It was called from function <module>
2023-06-19 11:16:17,856 ERROR server.py Client ('127.0.0.1', 62419) disconnected, error [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2023-06-19 11:16:17,857 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=500, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62419)>]), kwargs: {}. It was called from function <module>
2023-06-19 11:16:51,088 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 11:16:51,089 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function server.main()
2023-06-19 11:16:51,094 ERROR server.py Something went wrong: [WinError 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
2023-06-19 11:16:51,686 INFO server.py The connection was set - client: <socket.socket fd=508, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62770)>, address: ('127.0.0.1', 62770)
2023-06-19 11:16:55,706 INFO server.py Function get_message was called - args: (<socket.socket fd=508, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62770)>,), kwargs: {}. It was called from function <module>
2023-06-19 11:16:55,707 INFO server.py Received message from client tomato: {'action': 'presence', 'time': 1687162615.397885, 'user': {'username': 'tomato', 'status': 'online'}, 'type': 'status'}
2023-06-19 11:16:55,707 INFO server.py Function send_message was called - args: (<socket.socket fd=508, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62770)>, {'action': 'login', 'time': 1687162615.7070997, 'alert': 'error'}), kwargs: {}. It was called from function <module>
2023-06-19 11:16:55,707 INFO server.py Response message was sent: {'action': 'login', 'time': 1687162615.7070997, 'alert': 'error'}
2023-06-19 11:16:55,708 ERROR server.py Client ('127.0.0.1', 62770) disconnected, error too many values to unpack (expected 2)
2023-06-19 11:16:55,708 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=508, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62770)>]), kwargs: {}. It was called from function <module>
2023-06-19 11:33:13,432 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 11:33:13,434 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function server.main()
2023-06-19 11:33:13,440 ERROR server.py Something went wrong: [WinError 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
2023-06-19 11:33:14,020 INFO server.py The connection was set - client: <socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50930)>, address: ('127.0.0.1', 50930)
2023-06-19 11:33:23,069 INFO server.py Function get_message was called - args: (<socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50930)>,), kwargs: {}. It was called from function <module>
2023-06-19 11:33:23,069 INFO server.py Received message from client klm: {'action': 'presence', 'time': 1687163602.2099724, 'user': {'username': 'klm', 'status': 'online'}, 'type': 'status'}
2023-06-19 11:33:23,070 INFO server.py Function send_message was called - args: (<socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50930)>, {'action': 'login', 'time': 1687163603.0707648, 'alert': 'ok'}), kwargs: {}. It was called from function <module>
2023-06-19 11:33:23,070 INFO server.py Response message was sent: {'action': 'login', 'time': 1687163603.0707648, 'alert': 'ok'}
2023-06-19 11:33:23,071 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50930)>]), kwargs: {}. It was called from function <module>
2023-06-19 11:33:27,099 ERROR server.py Client ('127.0.0.1', 50930) disconnected, error [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2023-06-19 11:33:27,100 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=448, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50930)>]), kwargs: {}. It was called from function <module>
2023-06-19 11:34:51,363 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 11:34:51,365 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function server.main()
2023-06-19 11:34:51,371 ERROR server.py Something went wrong: [WinError 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
2023-06-19 11:34:51,918 INFO server.py The connection was set - client: <socket.socket fd=516, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51319)>, address: ('127.0.0.1', 51319)
2023-06-19 11:34:58,957 INFO server.py Function get_message was called - args: (<socket.socket fd=516, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51319)>,), kwargs: {}. It was called from function <module>
2023-06-19 11:34:58,959 INFO server.py Received message from client qwerty: {'action': 'presence', 'time': 1687163698.7583854, 'user': {'username': 'qwerty', 'status': 'online'}, 'type': 'status'}
2023-06-19 11:34:58,959 INFO server.py Function send_message was called - args: (<socket.socket fd=516, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51319)>, {'action': 'login', 'time': 1687163698.9590113, 'alert': 'ok'}), kwargs: {}. It was called from function <module>
2023-06-19 11:34:58,959 INFO server.py Response message was sent: {'action': 'login', 'time': 1687163698.9590113, 'alert': 'ok'}
2023-06-19 11:34:58,959 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=516, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51319)>]), kwargs: {}. It was called from function <module>
2023-06-19 11:35:15,087 ERROR server.py Client ('127.0.0.1', 51319) disconnected, error [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2023-06-19 11:35:15,088 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=516, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51319)>]), kwargs: {}. It was called from function <module>
2023-06-19 11:39:29,707 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 11:39:29,710 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function server.main()
2023-06-19 11:39:29,718 ERROR server.py Something went wrong: [WinError 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
2023-06-19 11:39:30,251 INFO server.py The connection was set - client: <socket.socket fd=488, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52420)>, address: ('127.0.0.1', 52420)
2023-06-19 11:40:29,716 INFO server.py Function get_message was called - args: (<socket.socket fd=488, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52420)>,), kwargs: {}. It was called from function <module>
2023-06-19 11:40:29,717 INFO server.py Received message from client Elsa: {'action': 'presence', 'time': 1687164029.1400955, 'user': {'username': 'Elsa', 'status': 'online'}, 'type': 'status'}
2023-06-19 11:40:29,718 INFO server.py Function send_message was called - args: (<socket.socket fd=488, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52420)>, {'action': 'login', 'time': 1687164029.7175016, 'alert': 'ok'}), kwargs: {}. It was called from function <module>
2023-06-19 11:40:29,718 INFO server.py Response message was sent: {'action': 'login', 'time': 1687164029.7175016, 'alert': 'ok'}
2023-06-19 11:40:29,718 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=488, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52420)>]), kwargs: {}. It was called from function <module>
2023-06-19 11:40:45,691 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 11:40:45,706 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function main()
2023-06-19 11:40:45,706 ERROR server.py Something went wrong: [WinError 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
2023-06-19 11:40:46,109 INFO server.py The connection was set - client: <socket.socket fd=508, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52929)>, address: ('127.0.0.1', 52929)
2023-06-19 11:40:50,149 INFO server.py Function get_message was called - args: (<socket.socket fd=508, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52929)>,), kwargs: {}. It was called from function <module>
2023-06-19 11:40:50,149 INFO server.py Received message from client Elsa: {'action': 'presence', 'time': 1687164050.1178985, 'user': {'username': 'Elsa', 'status': 'online'}, 'type': 'status'}
2023-06-19 11:40:50,149 INFO server.py Function send_message was called - args: (<socket.socket fd=508, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52929)>, {'action': 'login', 'time': 1687164050.1492174, 'alert': 'error'}), kwargs: {}. It was called from function <module>
2023-06-19 11:40:50,149 INFO server.py Response message was sent: {'action': 'login', 'time': 1687164050.1492174, 'alert': 'error'}
2023-06-19 11:40:50,149 ERROR server.py Client ('127.0.0.1', 52929) disconnected, error too many values to unpack (expected 2)
2023-06-19 11:40:50,149 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000019D8A67EB90>, [<socket.socket fd=508, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52929)>]), kwargs: {}. It was called from function <module>
2023-06-19 11:41:34,920 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 11:41:34,920 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function main()
2023-06-19 11:41:34,920 INFO server.py Socket was successfully created
2023-06-19 11:41:34,920 INFO server.py Function init_socket was called - args: (<__main__.Server object at 0x0000021025546690>,), kwargs: {}. It was called from function main()
2023-06-19 11:41:35,379 INFO server.py The connection was set - client: <socket.socket fd=784, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53128)>, address: ('127.0.0.1', 53128)
2023-06-19 11:42:02,132 INFO server.py Function get_message was called - args: (<socket.socket fd=784, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53128)>,), kwargs: {}. It was called from function main()
2023-06-19 11:42:18,970 INFO server.py Received message from client Ann: {'action': 'presence', 'time': 1687164112.8763015, 'user': {'username': 'Ann', 'status': 'online'}, 'type': 'status'}
2023-06-19 11:42:28,808 INFO server.py Function send_message was called - args: (<socket.socket fd=784, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53128)>, {'action': 'login', 'time': 1687164146.7933486, 'alert': 'ok'}), kwargs: {}. It was called from function main()
2023-06-19 11:42:31,935 INFO server.py Response message was sent: {'action': 'login', 'time': 1687164146.7933486, 'alert': 'ok'}
2023-06-19 11:42:48,054 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000021025546690>, [<socket.socket fd=784, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53128)>]), kwargs: {}. It was called from function main()
2023-06-19 12:01:04,954 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 12:01:04,954 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function main()
2023-06-19 12:01:04,969 INFO server.py Socket was successfully created
2023-06-19 12:01:04,969 INFO server.py Function init_socket was called - args: (<__main__.Server object at 0x0000028ED4EC6710>,), kwargs: {}. It was called from function main()
2023-06-19 12:01:05,250 INFO server.py The connection was set - client: <socket.socket fd=824, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57907)>, address: ('127.0.0.1', 57907)
2023-06-19 12:01:25,860 INFO server.py Function get_message was called - args: (<socket.socket fd=824, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57907)>,), kwargs: {}. It was called from function main()
2023-06-19 12:01:32,072 INFO server.py Received message from client Olaf: {'action': 'presence', 'time': 1687165273.192767, 'user': {'username': 'Olaf', 'status': 'online'}, 'type': 'status'}
2023-06-19 12:01:35,510 INFO server.py Function send_message was called - args: (<socket.socket fd=824, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57907)>, {'action': 'login', 'time': 1687165294.887475, 'alert': 'ok'}), kwargs: {}. It was called from function main()
2023-06-19 12:03:38,583 INFO server.py Response message was sent: {'action': 'login', 'time': 1687165294.887475, 'alert': 'ok'}
2023-06-19 12:03:38,585 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000028ED4EC6710>, [<socket.socket fd=824, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57907)>]), kwargs: {}. It was called from function main()
2023-06-19 12:03:39,594 ERROR server.py Client ('127.0.0.1', 57907) disconnected, error [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2023-06-19 12:03:39,595 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000028ED4EC6710>, [<socket.socket fd=824, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57907)>]), kwargs: {}. It was called from function main()
2023-06-19 12:03:41,635 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 12:03:41,636 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function server.main()
2023-06-19 12:03:41,640 ERROR server.py Something went wrong: [WinError 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
2023-06-19 12:03:42,235 INFO server.py The connection was set - client: <socket.socket fd=1372, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58534)>, address: ('127.0.0.1', 58534)
2023-06-19 12:03:46,264 INFO server.py Function get_message was called - args: (<socket.socket fd=1372, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58534)>,), kwargs: {}. It was called from function main()
2023-06-19 12:03:46,264 INFO server.py Received message from client Elsa: {'action': 'presence', 'time': 1687165425.2822316, 'user': {'username': 'Elsa', 'status': 'online'}, 'type': 'status'}
2023-06-19 12:03:46,265 INFO server.py Function send_message was called - args: (<socket.socket fd=1372, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58534)>, {'action': 'login', 'time': 1687165426.2646606, 'alert': 'ok'}), kwargs: {}. It was called from function main()
2023-06-19 12:03:46,267 INFO server.py Response message was sent: {'action': 'login', 'time': 1687165426.2646606, 'alert': 'ok'}
2023-06-19 12:03:46,268 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000028ED4EC6710>, [<socket.socket fd=1372, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58534)>]), kwargs: {}. It was called from function main()
2023-06-19 12:03:49,304 INFO server.py Function get_message was called - args: (<socket.socket fd=1372, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58534)>,), kwargs: {}. It was called from function main()
2023-06-19 12:03:49,304 INFO server.py Received message from client Elsa: {'action': 'quit', 'time': 1687165428.7170632, 'user': {'username': 'Elsa'}}
2023-06-19 12:03:49,305 ERROR server.py Client ('127.0.0.1', 58534) disconnected, error too many values to unpack (expected 2)
2023-06-19 12:03:49,306 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000028ED4EC6710>, [<socket.socket fd=1372, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58534)>]), kwargs: {}. It was called from function main()
2023-06-19 12:05:00,962 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 12:05:00,978 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function main()
2023-06-19 12:05:00,978 ERROR server.py Something went wrong: [WinError 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
2023-06-19 12:05:01,362 INFO server.py The connection was set - client: <socket.socket fd=1376, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58855)>, address: ('127.0.0.1', 58855)
2023-06-19 12:05:05,398 INFO server.py Function get_message was called - args: (<socket.socket fd=1376, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58855)>,), kwargs: {}. It was called from function main()
2023-06-19 12:05:05,398 INFO server.py Received message from client Olaf: {'action': 'presence', 'time': 1687165504.5065622, 'user': {'username': 'Olaf', 'status': 'online'}, 'type': 'status'}
2023-06-19 12:05:05,398 INFO server.py Function send_message was called - args: (<socket.socket fd=1376, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58855)>, {'action': 'login', 'time': 1687165505.39889, 'alert': 'error'}), kwargs: {}. It was called from function main()
2023-06-19 12:05:05,398 INFO server.py Response message was sent: {'action': 'login', 'time': 1687165505.39889, 'alert': 'error'}
2023-06-19 12:05:05,398 ERROR server.py Client ('127.0.0.1', 58855) disconnected, error too many values to unpack (expected 2)
2023-06-19 12:05:05,404 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x0000028ED4EC6710>, [<socket.socket fd=1376, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58855)>]), kwargs: {}. It was called from function main()
2023-06-19 12:05:34,630 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 12:05:34,630 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function main()
2023-06-19 12:05:34,630 INFO server.py Socket was successfully created
2023-06-19 12:05:34,630 INFO server.py Function init_socket was called - args: (<__main__.Server object at 0x000001E987B66790>,), kwargs: {}. It was called from function main()
2023-06-19 12:05:34,942 INFO server.py The connection was set - client: <socket.socket fd=864, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58991)>, address: ('127.0.0.1', 58991)
2023-06-19 12:05:47,344 INFO server.py Function get_message was called - args: (<socket.socket fd=864, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58991)>,), kwargs: {}. It was called from function main()
2023-06-19 12:05:53,396 INFO server.py Received message from client Lol: {'action': 'presence', 'time': 1687165542.04389, 'user': {'username': 'Lol', 'status': 'online'}, 'type': 'status'}
2023-06-19 12:06:01,569 INFO server.py Function send_message was called - args: (<socket.socket fd=864, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58991)>, {'action': 'login', 'time': 1687165560.999567, 'alert': 'ok'}), kwargs: {}. It was called from function main()
2023-06-19 12:08:42,012 INFO server.py Response message was sent: {'action': 'login', 'time': 1687165560.999567, 'alert': 'ok'}
2023-06-19 12:08:42,012 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x000001E987B66790>, [<socket.socket fd=864, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58991)>]), kwargs: {}. It was called from function main()
2023-06-19 12:08:43,024 INFO server.py Function get_message was called - args: (<socket.socket fd=864, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58991)>,), kwargs: {}. It was called from function main()
2023-06-19 12:08:43,025 INFO server.py Received message from client Lol: {'action': 'quit', 'time': 1687165575.0798483, 'user': {'username': 'Lol'}}
2023-06-19 12:08:43,026 ERROR server.py Client ('127.0.0.1', 58991) disconnected, error too many values to unpack (expected 2)
2023-06-19 12:08:43,027 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x000001E987B66790>, [<socket.socket fd=864, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58991)>]), kwargs: {}. It was called from function main()
2023-06-19 12:08:45,673 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 12:08:45,675 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function server.main()
2023-06-19 12:08:45,683 ERROR server.py Something went wrong: [WinError 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
2023-06-19 12:08:46,275 INFO server.py The connection was set - client: <socket.socket fd=720, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59756)>, address: ('127.0.0.1', 59756)
2023-06-19 12:08:58,397 INFO server.py Function get_message was called - args: (<socket.socket fd=720, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59756)>,), kwargs: {}. It was called from function main()
2023-06-19 12:08:58,398 INFO server.py Received message from client Stefan: {'action': 'presence', 'time': 1687165737.9322772, 'user': {'username': 'Stefan', 'status': 'online'}, 'type': 'status'}
2023-06-19 12:08:58,399 INFO server.py Function send_message was called - args: (<socket.socket fd=720, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59756)>, {'action': 'login', 'time': 1687165738.3985388, 'alert': 'ok'}), kwargs: {}. It was called from function main()
2023-06-19 12:08:58,399 INFO server.py Response message was sent: {'action': 'login', 'time': 1687165738.3985388, 'alert': 'ok'}
2023-06-19 12:08:58,400 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x000001E987B66790>, [<socket.socket fd=720, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59756)>]), kwargs: {}. It was called from function main()
2023-06-19 12:09:00,418 INFO server.py Function get_message was called - args: (<socket.socket fd=720, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59756)>,), kwargs: {}. It was called from function main()
2023-06-19 12:09:00,418 INFO server.py Received message from client Stefan: {'action': 'quit', 'time': 1687165740.130111, 'user': {'username': 'Stefan'}}
2023-06-19 12:09:00,419 ERROR server.py Client ('127.0.0.1', 59756) disconnected, error too many values to unpack (expected 2)
2023-06-19 12:09:00,420 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x000001E987B66790>, [<socket.socket fd=720, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59756)>]), kwargs: {}. It was called from function main()
2023-06-19 12:11:45,339 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 12:11:45,341 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function server.main()
2023-06-19 12:11:45,347 INFO server.py Socket was successfully created
2023-06-19 12:11:45,348 INFO server.py Function init_socket was called - args: (<__main__.Server object at 0x00000232335AEA10>,), kwargs: {}. It was called from function server.main()
2023-06-19 12:11:45,979 INFO server.py The connection was set - client: <socket.socket fd=500, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60488)>, address: ('127.0.0.1', 60488)
2023-06-19 12:11:55,053 INFO server.py Function get_message was called - args: (<socket.socket fd=500, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60488)>,), kwargs: {}. It was called from function server.main()
2023-06-19 12:11:55,054 INFO server.py Received message from client Helen: {'action': 'presence', 'time': 1687165914.742447, 'user': {'username': 'Helen', 'status': 'online'}, 'type': 'status'}
2023-06-19 12:11:55,054 INFO server.py Function send_message was called - args: (<socket.socket fd=500, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60488)>, {'action': 'login', 'time': 1687165915.054864, 'alert': 'ok'}), kwargs: {}. It was called from function server.main()
2023-06-19 12:11:55,055 INFO server.py Response message was sent: {'action': 'login', 'time': 1687165915.054864, 'alert': 'ok'}
2023-06-19 12:11:55,055 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x00000232335AEA10>, [<socket.socket fd=500, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60488)>]), kwargs: {}. It was called from function server.main()
2023-06-19 12:11:58,081 INFO server.py Function get_message was called - args: (<socket.socket fd=500, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60488)>,), kwargs: {}. It was called from function server.main()
2023-06-19 12:11:58,096 INFO server.py Received message from client Helen: {'action': 'quit', 'time': 1687165917.8552668, 'user': {'username': 'Helen'}}
2023-06-19 12:11:58,097 ERROR server.py Client ('127.0.0.1', 60488) disconnected, error too many values to unpack (expected 2)
2023-06-19 12:11:58,098 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x00000232335AEA10>, [<socket.socket fd=500, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60488)>]), kwargs: {}. It was called from function server.main()
2023-06-19 12:13:58,417 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 12:13:58,433 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function main()
2023-06-19 12:13:58,433 ERROR server.py Something went wrong: [WinError 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
2023-06-19 12:13:58,833 INFO server.py The connection was set - client: <socket.socket fd=496, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 61018)>, address: ('127.0.0.1', 61018)
2023-06-19 12:14:43,149 INFO server.py Function get_message was called - args: (<socket.socket fd=496, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 61018)>,), kwargs: {}. It was called from function server.main()
2023-06-19 12:14:43,149 INFO server.py Received message from client Eminem: {'action': 'presence', 'time': 1687166082.583834, 'user': {'username': 'Eminem', 'status': 'online'}, 'type': 'status'}
2023-06-19 12:14:43,149 INFO server.py Function send_message was called - args: (<socket.socket fd=496, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 61018)>, {'action': 'login', 'time': 1687166083.14944, 'alert': 'ok'}), kwargs: {}. It was called from function server.main()
2023-06-19 12:14:43,149 INFO server.py Response message was sent: {'action': 'login', 'time': 1687166083.14944, 'alert': 'ok'}
2023-06-19 12:14:43,149 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x00000232335AEA10>, [<socket.socket fd=496, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 61018)>]), kwargs: {}. It was called from function server.main()
2023-06-19 12:15:26,537 INFO server.py Function get_message was called - args: (<socket.socket fd=496, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 61018)>,), kwargs: {}. It was called from function server.main()
2023-06-19 12:15:26,537 INFO server.py Received message from client Eminem: {'action': 'quit', 'time': 1687166120.780035, 'user': {'username': 'Eminem'}}
2023-06-19 12:15:26,537 ERROR server.py Client ('127.0.0.1', 61018) disconnected, error too many values to unpack (expected 2)
2023-06-19 12:15:26,538 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x00000232335AEA10>, [<socket.socket fd=496, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 61018)>]), kwargs: {}. It was called from function server.main()
2023-06-19 12:20:07,165 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 12:20:07,183 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function main()
2023-06-19 12:20:07,188 INFO server.py Socket was successfully created
2023-06-19 12:20:07,190 INFO server.py Function init_socket was called - args: (<__main__.Server object at 0x00000182D51669D0>,), kwargs: {}. It was called from function main()
2023-06-19 12:20:07,561 INFO server.py The connection was set - client: <socket.socket fd=872, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62496)>, address: ('127.0.0.1', 62496)
2023-06-19 12:20:18,749 INFO server.py Function get_message was called - args: (<socket.socket fd=872, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62496)>,), kwargs: {}. It was called from function main()
2023-06-19 12:20:22,145 INFO server.py Received message from client Hahaha: {'action': 'presence', 'time': 1687166412.8609145, 'user': {'username': 'Hahaha', 'status': 'online'}, 'type': 'status'}
2023-06-19 12:20:26,259 INFO server.py Function send_message was called - args: (<socket.socket fd=872, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 62496)>, {'action': 'login', 'time': 1687166425.5975158, 'alert': 'ok'}), kwargs: {}. It was called from function main()
2023-06-19 12:34:41,270 INFO server.py IP-address: localhost, TCP-port: 7777
2023-06-19 12:34:41,272 INFO server.py Function parse_params was called - args: (), kwargs: {}. It was called from function server.main()
2023-06-19 12:34:41,281 INFO server.py Socket was successfully created
2023-06-19 12:34:41,282 INFO server.py Function init_socket was called - args: (<__main__.Server object at 0x000001EAE2A42B10>,), kwargs: {}. It was called from function server.main()
2023-06-19 12:34:41,883 INFO server.py The connection was set - client: <socket.socket fd=356, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49875)>, address: ('127.0.0.1', 49875)
2023-06-19 12:34:50,981 INFO server.py Function get_message was called - args: (<socket.socket fd=356, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49875)>,), kwargs: {}. It was called from function server.main()
2023-06-19 12:34:50,981 INFO server.py Received message from client Piter Pen: {'action': 'presence', 'time': 1687167290.6847782, 'user': {'username': 'Piter Pen', 'status': 'online'}, 'type': 'status'}
2023-06-19 12:34:50,997 INFO server.py Function send_message was called - args: (<socket.socket fd=356, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49875)>, {'action': 'login', 'time': 1687167290.9965937, 'alert': 'ok'}), kwargs: {}. It was called from function server.main()
2023-06-19 12:34:50,997 INFO server.py Response message was sent: {'action': 'login', 'time': 1687167290.9965937, 'alert': 'ok'}
2023-06-19 12:34:50,998 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x000001EAE2A42B10>, [<socket.socket fd=356, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49875)>]), kwargs: {}. It was called from function server.main()
2023-06-19 12:34:54,036 INFO server.py Function get_message was called - args: (<socket.socket fd=356, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49875)>,), kwargs: {}. It was called from function server.main()
2023-06-19 12:34:54,036 INFO server.py Received message from client Piter Pen: {'action': 'quit', 'time': 1687167293.5132716, 'user': {'username': 'Piter Pen'}}
2023-06-19 12:34:54,037 ERROR server.py Client ('127.0.0.1', 49875) disconnected, error too many values to unpack (expected 2)
2023-06-19 12:34:54,037 INFO server.py Function check_requests was called - args: (<__main__.Server object at 0x000001EAE2A42B10>, [<socket.socket fd=356, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49875)>]), kwargs: {}. It was called from function server.main()
